FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /workspace/pre-process/common/database

COPY requirements /tmp/requirements
COPY common/database/requirements-migrations.txt /tmp/common/database/requirements-migrations.txt

RUN pip install --no-cache-dir -r /tmp/common/database/requirements-migrations.txt

COPY common/database/docker-entrypoint-migrations.sh /usr/local/bin/preprocess-db-migrations

RUN chmod +x /usr/local/bin/preprocess-db-migrations

ENTRYPOINT ["preprocess-db-migrations"]
CMD ["apply"]
